### ISSUE TITLE
TypeError: this._machinomy.requireOpenChannel is not a function

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-ethereum-asym-client#1]
Investigating.

**Comment by michielbdejong** [comment]
From https://github.com/machinomy/machinomy/blob/master/docs/architecture.md it looks like it should be channelManager.requireOpenChannel

**Comment by michielbdejong** [comment]
this._machinomy.channelManager.requireOpenChannel exists, but channelManager is a private field of the Machinomy object.

**Comment by ukstv** [comment]
...and confusion begins due to different versions of the package. Yahoo! Let me fix that field availability in an upstream version, not the one we use for the client here.

**Comment by michielbdejong** [comment]
ok! I'm trying to switch the dependency to require the master branch from github, but it seems it doesn't compile from TS to JS when I do that.

**Comment by michielbdejong** [comment]
Fixed in https://github.com/michielbdejong/ilp-plugin-ethereum-asym-client/commit/c46b86df5269182638a40893c7546fc7209627ca on my fork.
