### ISSUE TITLE
Error: Unidirectional has not been deployed to detected network (network/artifact mismatch)

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-ethereum-asym-client#4]
Investigating.

**Comment by michielbdejong** [comment]
```sh
  machinomy:ChannelContract Creating channel. Value: 1000 / Settlement: 172800 +0ms
(node:29073) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unidirectional has not been deployed to detected network (network/artifact mismatch)
(node:29073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michielbdejong** [comment]
I guess the "detected network" is probably Rinkeby and "Unidirectional" probably refers to `node_modules/machinomy/node_modules/@machinomy/contracts/dist/build/contracts/Unidirectional.json`

**Comment by ukstv** [comment]
That’s true. Unidirectional on master is deployed only on Ropsten for now. I started deploying it half an hour ago on Rinkeby, and got an extremely strange error on Truffle: it does not detect correct state of the network altogether. I’ll keep you posted when it’s on Rinkeby. Meanwhile, how do you feel about deploying the contract on Ganache?

**Comment by michielbdejong** [comment]
Hm, since my goal is to connect the testnets of various cryptocurrencies, I would like to be either on Rinkeby or on Ropsten, not on a private Ganache net. So I guess the three options are:

* wait and see if the problem deploying unidirectional to Rinkeby goes away somehow
* are there any contracts on Rinkeby that I could use instead of current master Unidirectional?
* I could just use Ropsten instead (will at least start syncing it, both on Amundsen and on my laptop)

**Comment by ukstv** [comment]
It is deployed on Rinkeby now. Ropsten is coming.

**Comment by michielbdejong** [comment]
oh, great! let me test.

**Comment by michielbdejong** [comment]
I've got a bad block in Rinkeby on my laptop, not sure if there's an easier way to recover from that, but I think I'll delete the database and sync from scratch when I get home.

**Comment by ukstv** [comment]
Usually it takes time to just download further blocks.

**Comment by michielbdejong** [comment]
Hm, I'm using infura which is synced up to block 1857458, but still get the same error...

edit: when using infura, i haven't given it access to my account, so that may affect things. i'll try with geth tomorrow once synced, and will also look into  https://gist.github.com/raineorshine/c8b30db96d7532e15f85fcfe72ac719c which might work as an approach to using infura instead of geth...

**Comment by michielbdejong** [comment]
Fixed!

**Comment by pdmendki** [comment]
Its missing on kovan testnet. Can someone deploy it ?
