### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by sentientwaffle** [interledgerjs/ilp-plugin-ethereum-asym-client#7]
Running the infura test script (with `machinomy@1.6.1`) fails with

```
Error: Cannot find module 'machinomy/dist/lib/Payment'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

When the require() is lower-cased, it fails with:

```
(node:8718) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): BigNumber Error: new BigNumber() not a number: undefined
```

instead. It looks like the `machinomy.nextPayment` API has changed.

**Comment by kincaidoneil** [comment]
Fixed by https://github.com/interledgerjs/ilp-plugin-ethereum-asym-client/commit/618fed9cd7ff5d612d05b9d91697e12886f64abe.
